### ISSUE TITLE
end crystals dont register properly (also update the maven example)

### ISSUE THREAD

**Issue by im-a-blobfish** [YeetmanLord/RayCastUtility#1]
java.lang.NoSuchMethodException: org.bukkit.craftbukkit.v1_8_R3.entity.CraftEnderCrystal.getBoundingBox()

im quite new to java btw

do I need to add another repository to my pom.xml? currently using spigot-api (1.8.8) and raycastutility

since this uses NMS, does something additional have to be done for this to work

thanks

**Comment by im-a-blobfish** [comment]
FIXED!!!

on both the spigot and github, you say to use 
<version>1.1.0</version>
with maven

though switching to 1.3.0 fixes my issue

**Comment by im-a-blobfish** [comment]
though, the raycasts seem to be quite unreliable with some specific entities - in my case, end crystals on 1.8.8, which is what I am using the utility to detect - they hardly ever get detected even though they have massive hitboxes

**Comment by im-a-blobfish** [comment]
on further investigation, with ender crystals, it only detects approximately the bottom 1/4 of the crystal, aiming above that will not be detected

**Comment by max-widmaier** [comment]
Oops, I will update that. That's a little odd however, that really has to do with Minecrafts bounding boxes unfortunately. You can try using a higher precision, that may help.

**Comment by adamj454545** [comment]
no, I had visual bounding boxes enabled and could see that only around the bottom 1/4 of the crystal would ever be detected in raycast no matter the precision - aiming above this area yet well within the bounding box would not be detected
