### ISSUE TITLE
incorrect example

### ISSUE THREAD

**Issue by im-a-blobfish** [YeetmanLord/RayCastUtility#2]
in the “Kill the entity the player is looking” example, you used the precision ACCURATE_BLOCK

as it is searching for entities, wouldnt it be better to use ACCURATE_ENTITY

anyways, back to my precious (closed) issue with endear crystals, ender crystals have large cube bounding boxes - they are not thin, and the upper 3/4 of the bounding box (I had bounding box outlines enabled) was never detected by raycasts, even though this area is about a block tall and more than a block thick, MUCH more than enough for even the inaccurate raycast to detect. if it is a vanilla game issue, could you explain this issue so I understand it - I really need this to work correctly for the plugin I am creating

**Comment by max-widmaier** [comment]
That's weird. I'll have to check some NMS stuff when I can. I'll get back to you as soon as I can.

**Comment by im-a-blobfish** [comment]
this is really odd. it seems to be more like the angle that the player is looking , as when flying in different positions, suddenly the raycasting works better higher up the bounding box

**Comment by im-a-blobfish** [comment]
IVE FOUND ITTTT

and its not just ender crystals - ive found that its EVERY entity


aiming with a pitch around 0 degrees makes entityraycasts just not work and return null (1.8.8)

no clue why

**Comment by max-widmaier** [comment]
There is very very weird.

**Comment by im-a-blobfish** [comment]
hey! since its been 5 days, I was wondering if you were planning on looking into this soon as it is a severe bug which completely stops my plugin from working correctly as nothing is registered when looking close to straight forwards, or if I should try to implement something myself if you're busy

**Comment by max-widmaier** [comment]
Oh, sorry I forgot!

**Comment by max-widmaier** [comment]
Ok, should be fixed. The raycasating gets a little finicky if there are blocks inside the end crystal's bounding box. (Next to it not below it). Otherwise, detection is far more accurate.

**Comment by max-widmaier** [comment]
Update to version 1.3.1 which has those fixes

**Comment by im-a-blobfish** [comment]
thanks!

**Comment by im-a-blobfish** [comment]
just curious, what was the the problem with the code before?

**Comment by max-widmaier** [comment]
Basically, I have to do a lot of stuff for performance so I limit the amount of entities that you can raytrace. I was doing it by location rather by it bounding box.

**Comment by im-a-blobfish** [comment]
ahh, I see

what do you think the performance difference would be be between your method of detecting collisions and just using something like world.getNearbyEntities(location, 0.1, 0.1, 0.1)

performance is very important for me as depending on player count, raycasts could be done many times per tick

**Comment by max-widmaier** [comment]
The performance is much better than that. I basically get all the entities that are only in the path of the raytrace by using the starting and ending positions for the cast. Then I filter by whether the entity intersects that bounding box.
