### ISSUE TITLE
version 1.3.1 from jitpack dosent work

### ISSUE THREAD

**Issue by im-a-blobfish** [YeetmanLord/RayCastUtility#3]
![image](https://user-images.githubusercontent.com/94757022/217895983-fd03b725-5eb2-4400-88c4-64dc3384e413.png)

cant sync maven with the new version because theres no working built version on jitpack

**Comment by max-widmaier** [comment]
Ok, should be fixed. You might need to wait a bit though.

**Comment by im-a-blobfish** [comment]
![image](https://user-images.githubusercontent.com/94757022/217943507-a7419172-2e3a-41c8-8f37-efe4640165f9.png)


thanks, though does it not need to be manually rebuilt on jitpack?

**Comment by im-a-blobfish** [comment]
wait nvm, the new commit still dosent build

https://jitpack.io/com/github/YeetmanLord/RayCastUtility/5fef5f9932/build.log

also you switch from spigot to spigot-api, i thought you needed spigot as a depencency to use nms?

**Comment by max-widmaier** [comment]
Ok, should be fixed, new version is 1.3.1.1. I got it to successfully build on jitpack.
