### ISSUE TITLE
the new update made my issue worse

### ISSUE THREAD

**Issue by im-a-blobfish** [YeetmanLord/RayCastUtility#5]
https://www.youtube.com/watch?v=XDaX8tiyVsc

^ video is an example of the issue (weakness effect is used so the crystal cant manually be broken, chat messages show when the event for the raycast is called and when it actually hits the crystal, the crystal is broken)

before 1.3.1, aiming more downwards would work but aiming straight forward wouldnt and aiming high up would work

now aiming high up still works at some angles, aiming straight forward works and aiming more downwards dosent work at all anymore while before it worked

what

**Comment by max-widmaier** [comment]
*sigh* I swear it was working when I was testing it. I'll have to do some testing later.

**Comment by max-widmaier** [comment]
Right now though, I'm working on some AI stuff, so I don't think I will do fixes until like saturday or sunday.

**Comment by max-widmaier** [comment]
Ok, I'm just not gonna filter anything. It will just grab all entities in a radius from the entity of whatever distance you specify.
